module.exports = {
    "team_id": "9002",
    "is_national": "False",
    "name": "Arsenal",
    "country": "England",
    "founded": "1886",
    "leagues": "1204,1198,1199,1005",
    "venue_name": "Emirates Stadium",
    "venue_id": "1076",
    "venue_surface": "grass",
    "venue_address": "Queensland Road",
    "venue_city": "London",
    "venue_capacity": "60355",
    "coach_name": "A. Wenger",
    "coach_id": "110681",
    "squad": [
      {
        "id": "237",
        "name": "P. ÄŒech",
        "number": "33",
        "age": "33",
        "position": "G",
        "injured": "False",
        "minutes": "1710",
        "appearences": "19",
        "lineups": "19",
        "substitute_in": "0",
        "substitute_out": "0",
        "substitute_on_bench": "0",
        "goals": "0",
        "assists": "0",
        "yellowcards": "0",
        "redcards": "0"
      }
    ],
    "sidelined": [
      {
        "name": "Arteta",
        "description": "Calf Muscle Strain",
        "startdate": "22.11.15",
        "enddate": "string",
        "id": "2876"
      }
    ],
    "transfers_in": [
      {
        "id": "260313",
        "name": "D. Crowley",
        "date": "01.11.15",
        "from_team": "Barnsley",
        "team_id": "9021",
        "type": "Unknown"
      }
    ],
    "transfers_out": [
      {
        "id": "314515",
        "name": "S. O'Connor",
        "date": "26.11.15",
        "to_team": "York",
        "team_id": "9460",
        "type": "Loan"
      }
    ],
    "statistics": {
      "rank": "1",
      "wins": "12",
      "wins_home": "6",
      "wins_away": "6",
      "draws": "3",
      "draws_home": "2",
      "draws_away": "1",
      "losses": "4",
      "losses_home": "1",
      "losses_away": "3",
      "clean_sheets": "8",
      "clean_sheets_home": "4",
      "clean_sheets_away": "4",
      "goals": "33",
      "goals_home": "15",
      "goals_away": "18",
      "goals_conceded": "18",
      "goals_conceded_home": "6",
      "goals_conceded_away": "12",
      "avg_goals_per_game_scored": "1.74",
      "avg_goals_per_game_scored_home": "1.67",
      "avg_goals_per_game_scored_away": "1.80",
      "avg_goals_per_game_conceded": "0.95",
      "avg_goals_per_game_conceded_home": "0.67",
      "avg_goals_per_game_conceded_away": "1.20",
      "avg_first_goal_scored": "32m",
      "avg_first_goal_scored_home": "34m",
      "avg_first_goal_scored_away": "30m",
      "avg_first_goal_conceded": "39m",
      "avg_first_goal_conceded_home": "50m",
      "avg_first_goal_conceded_away": "31m",
      "failed_to_score": "4",
      "failed_to_score_home": "2",
      "failed_to_score_away": "2",
      "biggest_defeat": 0,
      "biggest_defeat_home": 0,
      "biggest_defeat_away": 0,
      "scoring_minutes_0_15_pct": "9.1%",
      "scoring_minutes_0_15_cnt": "3",
      "scoring_minutes_15_30_pct": "15.2%",
      "scoring_minutes_15_30_cnt": "5",
      "scoring_minutes_30_45_pct": "24.2%",
      "scoring_minutes_30_45_cnt": "8",
      "scoring_minutes_45_60_pct": "15.2%",
      "scoring_minutes_45_60_cnt": "5",
      "scoring_minutes_60_75_pct": "21.2%",
      "scoring_minutes_60_75_cnt": "7",
      "scoring_minutes_75_90_pct": "15.2%",
      "scoring_minutes_75_90_cnt": "5"
    }
  };